spring:
  application:
    name: pang-api-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    password: ${DB_PASSWORD}
    username: ${DB_USER}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: true
    url: ${DB_URL}
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    baseline-on-migrate: true
    locations: classpath:db/migration

app:
  token:
    access-token: ${TOKEN_ACCESS}
    refresh-token: ${TOKEN_REFRESH}
    secret: ${TOKEN_SECRET}

logging:
  level:
    org:
      springframework:
        security: DEBUG