spring:
  application:
    name: pang-api-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    password: ${DB_PASSWORD}
    username: ${DB_USER}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  flyway:
    enabled: true
    url: ${DB_URL}
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    baseline-on-migrate: true
    locations: classpath:db/migration
  data:
    redis:
      port: 6379
      host: ${REDIS_HOST}
      database: 0

springdoc:
  swagger-ui:
    display-request-duration: true

app:
  video:
    key: ${VIDEO_KEY}
  token:
    access-token: ${TOKEN_ACCESS}
    refresh-token: ${TOKEN_REFRESH}
    secret: ${TOKEN_SECRET}
  pg:
    sellerid: ${PAYAPP_PG_SELLERID}

logging:
  level:
    org:
      springframework:
        security: DEBUG