spring:
  application:
    name: pang-api-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    password: ${DB_PASSWORD}
    username: ${DB_USER}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
app:
  token:
    access-token: ${TOKEN_ACCESS}
    refresh-token: ${TOKEN_REFRESH}
    secret: ${TOKEN_SECRET}
  pg:
    sellerid: ${PAYAPP_PG_SELLERID}
    linkkey: ${PAYAPP_PG_LINKKEY}
    linkval: ${PAYAPP_PG_LINKVAL}

logging:
  level:
    org:
      springframework:
        security: DEBUG