spring:
  application:
    name: pang-api-server
app:
  token:
    access-token: 360000000
    refresh-token: 64000000000
    secret: dskjfasdjkfhasdflhkjadlhuvawerlkhvlhksdfhkvawluefghazsdlkg12e132lhawelkfawbrfliudb