spring:
  application:
    name: pang-api-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pang
    password: 1234
    username: root
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
app:
  token:
    access-token: ${TOKEN_ACCESS}
    refresh-token: ${TOKEN_REFRESH}
    secret: ${TOKEN_SECRET}