spring:
  application:
    name: pang-api-server
  cache:
    type: redis
    redis:
      time-to-live: 600000 # 10ë¶„
      cache-null-values: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    password: ${DB_PASSWORD}
    username: ${DB_USER}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: true
    url: ${DB_URL}
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    baseline-on-migrate: true
    locations: classpath:db/migration
  data:
    redis:
      port: 6379
      host: ${REDIS_HOST}
      database: 0
  servlet:
    multipart:
      maxFileSize: 150MB
      maxRequestSize: 150MB
  cloud:
    aws:
      region:
        static: ap-northeast-2
      stack:
        auto: false
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      s3:
        bucket: ${AWS_BUCKET}
  security:
    user:
      name: ${SWAGGER_USER}
      password: ${SWAGGER_PASSWORD}
  elasticsearch:
    username: ${ES_USER}
    password: ${ES_PASSWORD}
    uris: ${ES_HOST}

springdoc:
  swagger-ui:
    display-request-duration: true

app:
  stream:
    url: ${STREAM_URL}
  video:
    key: ${VIDEO_KEY}
  token:
    access-token: ${TOKEN_ACCESS}
    refresh-token: ${TOKEN_REFRESH}
    secret: ${TOKEN_SECRET}
  pg:
    sellerid: ${PAYAPP_PG_SELLERID}

logging:
  level:
    org:
      springframework:
        security: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
